services:
  app:
    build: .
    container_name: ciekm-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - app_default

networks:
  app_default:
    external: true 
